name: molzy
channels:
  - conda-forge
  - rdkit
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - jupyter
  - jupyterlab
  - ipykernel
  - openpyxl
  - rdkit
  - xgboost
  - pytorch
  - torchvision
  - torchaudio
  - torchinfo
  - h5py
  - torchmetrics
  - pip:
      - git+https://github.com/bp-kelley/descriptastorus.git
      - git+https://github.com/facebookresearch/esm.git
      - jaxtyping
      - dataclasses-json

